repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
        args: ["--profile", "black", "--filter-files"]
        exclude: /(migrations|_pb2|pycoin|gen)/

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        exclude: /(\\.eggs|\\.git|\\.hg|\\.mypy_cache|\\.nox|\\.tox|\\.venv|_build|buck-out|build|dist|migrations|_pb2|pycoin|gen)/

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3
        exclude: /(migrations|_pb2|gen)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: end-of-file-fixer
        exclude: /(migrations|_pb2|pycoin|deprecated|gen)/
        files: .*.py$
      - id: trailing-whitespace
        exclude: /(migrations|_pb2|pycoin|deprecated|gen)/
        files: .*.py$
      - id: file-contents-sorter
        files: ^(requirements.*.txt)$